DROP TABLE IF EXISTS member CASCADE;

CREATE TABLE member
(
    id       BIGINT PRIMARY KEY AUTO_INCREMENT,
    userid   VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    roles    VARCHAR(255) NOT NULL
);